# Generated by Django 5.1.3 on 2024-12-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                (
                    "content",
                    models.CharField(max_length=150, verbose_name="Содержимое"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/",
                        verbose_name="Изображение",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("publication_sign", models.BooleanField(default=False)),
                (
                    "number_of_views",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Стоимость"
                    ),
                ),
            ],
        ),
    ]
