# Generated by Django 5.1.3 on 2024-12-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="имя категории"),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="имя категории"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="описание продукта"
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                (
                    "category",
                    models.CharField(max_length=150, verbose_name="категория"),
                ),
                ("price", models.IntegerField(verbose_name="цена за покупку")),
                (
                    "created_at",
                    models.DateTimeField(blank=True, verbose_name="дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, verbose_name="дата последних изменений"
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
                "ordering": ["name", "category"],
            },
        ),
    ]
