# Generated by Django 5.1.3 on 2024-12-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="описание категории"
            ),
        ),
    ]
